### ISSUE TITLE
Gulpfile db_dump tasks.

### ISSUE THREAD

**Issue by dewald-laubscher** [fixate/generator-fixate-pw#12]
The db_dump tasks have a Date.now() function thats part of EMCA-262 5th edition, it is not working on my version of node, the issue might be my node version, however there is a fix according to MDN :
```javascript
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now#Polyfill
if (!Date.now) {
  Date.now = function now() {
    return new Date().getTime();
  };
}
```

**Comment by larrybotha** [comment]
fixed: https://github.com/fixate/generator-fixate-pw/commit/c8ceae4ab186595b8d2754fe3f1c6c9b0cbb930d
