### ISSUE TITLE
Cannot find module 'shelljs' on Windows 8.1

### ISSUE THREAD

**Issue by jmartsch** [fixate/generator-fixate-pw#14]
Hi. I cloned the git repo and changed into the directory and linked as described.
After that I created a new folder and ran ```yo fixate-pw``` and I get an error "Error: Cannot find module 'shelljs'". So I ran  ```npm install -g shelljs```  but after running ```yo fixate-pw``` again I still get the same error message. Any ideas how to solve this?

```javascript
Error: Cannot find module 'shelljs'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (W:\wamp\www\generator-fixate-pw\app\lib\git-utils.coffee:3:9)
  at Object.<anonymous> (W:\wamp\www\generator-fixate-pw\app\lib\git-utils.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (W:\wamp\www\generator-fixate-pw\node_modules\coffee-script\lib\coffee-script\register.js:16:19)
  at Module.load (W:\wamp\www\generator-fixate-pw\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (W:\wamp\www\generator-fixate-pw\app\generator.coffee:1:12)
  at Object.<anonymous> (W:\wamp\www\generator-fixate-pw\app\generator.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (W:\wamp\www\generator-fixate-pw\node_modules\coffee-script\lib\coffee-script\register.js:16:19)
  at Module.load (W:\wamp\www\generator-fixate-pw\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (W:\wamp\www\generator-fixate-pw\app\index.js:3:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object._storeAsPath.Object.defineProperty.get [as fixate-pw:app] (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
  at Store.get (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)
  at Environment.get (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:228:16)
  at Environment.create (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:246:24)
  at Environment.run (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:318:24)
  at C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\lib\cli.js:86:9
  at Environment.resolver.lookup (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:50:12)
  at init (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\lib\cli.js:61:7)
  at pre (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\lib\cli.js:48:3)
  at Object.<anonymous> (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\lib\cli.js:150:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:901:3
```

**Comment by larrybotha** [comment]
try installing shelljs directly into the generator's directory:

```shell
$ npm install shelljs
```

if you create a small node app requiring shelljs and run it, does it do anything?

e.g. app.js
```javascript
var shell = require('shelljs');
shell.echo('hello world');
```

```shell
$ node app.js
//=> hello world
```

If you can run this app where shelljs is locally installed, but not where it is globally installed, there is likely a mismatch between where global modules are installed, and where those modules are being looked for.

**Comment by jmartsch** [comment]
Yes. It echoes "Hello World" on console (Windows command prompt).


------ Originalnachricht ------
Von: "Larry Botha" <notifications@github.com>
An: "fixate/generator-fixate-pw" 
<generator-fixate-pw@noreply.github.com>
Cc: "Jens Martsch" <jmartsch@gmail.com>
Gesendet: 07.04.2015 12:03:45
Betreff: Re: [generator-fixate-pw] Cannot find module 'shelljs' on 
Windows 8.1 (#14)

**Comment by larrybotha** [comment]
Does it work globally, or only in the generator's folder?

Does your generator now run, after installing shelljs locally?

**Comment by jmartsch** [comment]
It only works in the generator´s folder. When I run it globally it get the same "Error: Cannot find module 'shelljs'" as before. The generator does not run with locally installed shelljs. It seems the generator looks for the global shelljs which can not be found. But I also did a ```npm install -g shelljs``` without errors.

**Comment by jmartsch** [comment]
After installing shelljs i get this:
```PS W:\wamp\www\fixate-test> npm install -g shelljs
npm http GET https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/shelljs
C:\Users\Aceman\AppData\Roaming\npm\shjs -> C:\Users\Aceman\AppData\Roaming\npm\node_modules\shelljs\bin\shjs
shelljs@0.4.0 C:\Users\Aceman\AppData\Roaming\npm\node_modules\shelljs```

**Comment by larrybotha** [comment]
not sure what's going on here. Looks like it's installed without issue. Also weird how the locally installed shelljs runs your app, but not in the generator.

Do you get any output with

```shell
$ which shjs
```
(not sure if 'which' is even a command on Windows)

Try clear your npm cache and reinstall dependencies. Pull changes - I've added shelljs as a dependency, too.

```shell
$ rm -rf node_modules/ && npm cache clean && npm install
```

**Comment by jmartsch** [comment]
Thanks for your suggestions.

I ran npm install in the cloned generator-fixate-pw directory and now it 
works.
There were no instructions to run "npm install" after cloning in the 
README.md.

Now I have a different problem, as tar is not available on windows. 
Maybe this can´t be run on windows?

the command "tar" could not be found.

events.js:74
         throw TypeError('Uncaught, unspecified "error" event.');
               ^
TypeError: Uncaught, unspecified "error" event.
   at TypeError (<anonymous>:null:null)
   at FixatePwGenerator.EventEmitter.emit (events.js:74:15)
   at 
W:\wamp\www\generator-fixate-pw\node_modules\yeoman-generator\lib\base.js:413:14
   at processImmediate [as _immediateCallback] (timers.js:330:15)


------ Originalnachricht ------
Von: "Larry Botha" <notifications@github.com>
An: "fixate/generator-fixate-pw" 
<generator-fixate-pw@noreply.github.com>
Cc: "Jens Martsch" <jmartsch@gmail.com>
Gesendet: 07.04.2015 12:28:44
Betreff: Re: [generator-fixate-pw] Cannot find module 'shelljs' on 
Windows 8.1 (#14)

**Comment by larrybotha** [comment]
Looks like tar is not supported on Windows by default.

Once you install Cygwin or MinGW you should have tar available as a command on the command line:
https://wiki.haskell.org/How_to_unpack_a_tar_file_in_Windows
http://superuser.com/questions/244703/how-can-i-run-the-tar-czf-command-in-windows

**Comment by larrybotha** [comment]
@jmartsch have you had any luck installing cygwin?

**Comment by jmartsch** [comment]
@larrybotha Not tried yet. I will try it later today and report back.

**Comment by jmartsch** [comment]
I installed MinGW and MSYS now and can run tar on the command line. When i run yo fixate-pw now I get another error: ```tar: W\:\\wamp\\www\fixate-test\\src: Cannot chdir: No such file or directory```
I think it´s because of the path: Windows paths are case-insensitive and use a backward slash (and MSYS does nothing to correct this behaviour). I also tried Cygwin, but there are other errors. I think the error is, that the backslash stands before the colon. It needs to be
```W:\wamp\www\fixate-test\src``` instead.
Can you tell me in which file the tar occurs? Maybe i can figure something out with the paths.

Here is the complete error message:
tar: W\:\\wamp\\www\fixate-test\\src: Cannot chdir: No such file or directory
tar: Error is not recoverable: exiting now

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
  at TypeError (<anonymous>:null:null)
  at FixatePwGenerator.EventEmitter.emit (events.js:74:15)
  at W:\wamp\www\generator-fixate-pw\node_modules\yeoman-generator\lib\base.js:413:14
  at processImmediate [as _immediateCallback] (timers.js:330:15)

**Comment by larrybotha** [comment]
`tar` is executed in [git-utils.coffee on ln 29](https://github.com/fixate/generator-fixate-pw/blob/master/app/lib/git-utils.coffee#L29). The line calling it, in your case, is in [generator.coffee on ln 97](https://github.com/fixate/generator-fixate-pw/blob/master/app/generator.coffee#L97).

Weird how the paths are being mangled like that - perhaps we need a flag specific for Windows that will tell it to use relative paths to avoid the unwanted `\`.

Give it a bash, and let me know how it works out. 

Perhaps archiving to a .zip, and then extract using zip rather than tar may resolve the issue:

```shell
# under Unix it would look something like this:
$ git archive --format=zip #{branch} | unzip -d #{dest_root}
```

**Comment by larrybotha** [comment]
another thing, on fresh generation, are the following folders at least being made?
```coffee
      @mkdir d for d in [
        'src',
        'database/dev',
        'database/prod',
        'styleguide'
      ]
```

**Comment by jmartsch** [comment]
Yes, they are generated, but empty or with empty subfolders.

**Comment by larrybotha** [comment]
hmm, just realised `this.mkdir` is a yo method, so that doesn't help us much in terms of what's going on with the command line :P 

anyways, let me know how you get along with things.

**Comment by jmartsch** [comment]
I wonder: Why don´t you clone the ProcessWire Repo directly to the project folder? You clone it in a cache dir in the generator-fixate-pw working dir, tar it, and then untar it in the project folder.

**Comment by larrybotha** [comment]
we do that so that when starting multiple PW projects in succession we don't download the full 12-13mb of the repo every time.

Instead we have a local cache of the live repo, which always has `git pull` executed on the specified branch for the repo. Much more efficient, especially for testing :)

What may be an option, if tar / zip is still giving you problems, is to copy the contents of the PW repo into your `src/` directlory.

Something like
```coffee
# git-utils.coffee

shell = require 'shelljs'
. 
.
.

(ln:29) shell.cp "-R", "./*", "#{dest_root}/*"
```

Let me know if you get that working - we may update the generator to rather work like this.

**Comment by jmartsch** [comment]
Hi Larry. I thought of exactly the same, and your reasons behind the cached repo.
I modified your code to
```javascript
shell.cp "-R", "./*", "#{dest_root}/"
```
without the * behind the dest_root and now it works.

Then I get a message: ```I'm all done. Running npm install & bower install for you to install the required dependencies. If this fails, try running the command yourself.```
but npm install & bower install are not beeing run. 

So i did a npm install by myself but it fails, as it wants to run the setup.sh which is a shell script that is very specific for Linux/Unix and can´t be run in this form on Windows. How important is the symlink? Will the styleguide work without it?

**Comment by larrybotha** [comment]
I noticed yesterday that `npm install && bower install` don't run automatically anymore - I think I've only experienced this since updating my yeoman. I'll be taking a look at that, but at least we can still run those commands manually :)

ye, that makes sense your symlinking would break. The styleguide will work without the symlink, but then you'll not see any of the production assets (i.e. built styles, bower components, images, fonts etc). You can do this manually, but it's a pain to remember.

We'd need to check in the shell script if we're on Unix / Windows, and run the command applicable to the system.

In the symlinking, something like this would check for windows, else run symlinking as per normal for Unix systems:

```shell
if ! [ -L styleguide/public/assets ]; then
	echo "assets not yet symlinked from styleguide -> symlinking"
	cd styleguide/public

	if [ "$OPSYS" == "cygwin] || [ "$OPSYS" == "msys"] || [ "$OPSYS == "win32"]; then
		// windows equiv. of symlink
	else
		ln -s ../../src/site/templates/assets assets
	fi
fi
```

Let me know how this works out for you - if you get everything to run in the script, I'll put your changes straight into the script.

**Comment by larrybotha** [comment]
we may have to check higher up if we're on Windows or not, I'm not sure if the '-L' flag is even available in Windows shells.

**Comment by jmartsch** [comment]
OK. I´ll  try to figure something out.

**Comment by larrybotha** [comment]
this may even come down to writing 2 entirely different bash scripts, and having setup.sh execute the relevant one based on `$OPSYS`

**Comment by larrybotha** [comment]
ye, nothing in that script is going to work for you unless you have a bash prompt installed. You'll likely need a .bat equivalent of that shell script.

If you have time to put together a .bat that mirrors setup.sh, it'd be much appreciated, but to get things working quickly, all you'll need to do is create a symlink in the styleguide to the assets in the site, and initialise a bower file.

**Comment by jmartsch** [comment]
Yeah, i am working on a batch script right now :)
One Problem is, that the mklink (ln -s equiv on windows) only can be run 
with an elevated (administrator) command prompt.

BTW: What does the -L flag do? Does it check if the directory exists?

**Comment by larrybotha** [comment]
it checks specifically if the directory is a symlink

**Comment by jmartsch** [comment]
So here is the setup.bat (just for creating the symlink, as the other stuff is too complicated for me right now).
 Remember: This has to be run with an adminstrator windows command prompt.
```
:: create a symlink from the styleguide to the production assets if one doesn't
:: already exist
@echo off

fsutil reparsepoint query "styleguide/public/assets" | find "Symbolic Link"
if %errorlevel% == 0 echo This is a symlink/junction
if %errorlevel% == 1 (
	rmdir /s /q styleguide\public\assets
	mklink /d "styleguide\public\assets" "..\..\src\site\templates\assets"
)
```
