### ISSUE TITLE
generator should download regularly used modules

### ISSUE THREAD

**Issue by larrybotha** [fixate/generator-fixate-pw#15]
generator should download the following modules along with the processwire install:

markupsimplenavigation
processredirects
sitemap

**Comment by dewald-laubscher** [comment]
I am uncertain as to how this should be implemented. For instance should I add processwire module section where these modules can be set, lets say inside the settings of the generator? Maybe make a default settings that can be overwritten by anything in settings? Then prompt the user if he did not set  any settings?

Alternatively just set them in settings and have the generator install.

@larrybotha

**Comment by larrybotha** [comment]
use a prompt to determine if the user wants it or not, [like from ln:27 of generator.coffee](https://github.com/fixate/generator-fixate-pw/blob/master/app/generator.coffee#L27-L40), and depending on the user input, you will either download or not download the module:

```coffee
    prompts.push
      type: "confirm"
      name: "usePWRedirects"
      message: "Install ProcessRedirects?"
      default: true
```

You can also set a list of Modules a user can tick or untick, and depending if the item is in the array, download the repo or not (the [same way the ProcessWire is downloaded](https://github.com/fixate/generator-fixate-pw/blob/master/app/generator.coffee#L96-L97))

This Angular generator has a good overview of how it can be done (don't use their prototyping convention):
https://github.com/yeoman/generator-angular/blob/master/app/index.js#L158-L221

**Comment by dewald-laubscher** [comment]
@larrybotha I like the list idea, however I have one final question. Should I implement the settings.json with an object called pw modules? (I would recommend under github object for clarification that the modules need to be on github for now.)

**Comment by larrybotha** [comment]
ye go for it

**Comment by dewald-laubscher** [comment]
Also, what about implementing the default modules idea? This will be the default list to be implemented on a question base, otherwise the user can set modules in settings to override the default, no questions needed and ignore default.

**Comment by larrybotha** [comment]
Generators shouldn't require modification to run. Generators are installed, and then run as is, so expecting users to modify settings within a generator falls outside of what a generator should do.

The generator sets up the project with defaults, the rest is up to the developer based on the project requirements.
i.e. install specifically required modules via the ProcessWire admin

**Comment by larrybotha** [comment]
a better solution is to prompt users for which modules to install, put those values in an array, and attempt to clone them into the  project.

The problem here, again, is that they have to go find all the repos, and supply all the links.

It's not a good allocation of time both for generator development, or the end user, especially since hte Process Wire admin handles this already.
