### ISSUE TITLE
secure the database details

### ISSUE THREAD

**Issue by dewwwald** [fixate/generator-fixate-pw#22]
Database details are being passed trough the shell, here the details are revealed through the process list.

Janne Pikkarainen ~ "Please note that from security point of view you should not provide user credentials on command line. Instead you should create a preference file ~/.myrc or so and fill the necessary information there. That way your user info won't be revealed through process list."
source: http://serverfault.com/questions/197656/mysqladmin-drop-database-bash-script

**Comment by larrybotha** [comment]
can be achieved by adding a sample .env for autoenv: https://github.com/kennethreitz/autoenv

**Comment by larrybotha** [comment]
config file should be specified in mysqldump command: http://stackoverflow.com/a/18871307/895007

will need to add template config files for dev and prod with ignores on actual files
