### ISSUE TITLE
Error: Missing positive glob when running uglify

### ISSUE THREAD

**Issue by jmartsch** [fixate/generator-fixate-pw#27]
I always get this error, so uglify fails.

Tried it with latest version right after ```yo fixate-pw```

**Comment by larrybotha** [comment]
is this still happening? I pushed a couple changes, and refactored all the rev'ing, minifying, and concatting

**Comment by jmartsch** [comment]
No it is not. Seems i did not pull correctly. That´s why i closed the issue.
