### ISSUE TITLE
Don´t use filenames in gulpfile, but instead in gulpconfig.json

### ISSUE THREAD

**Issue by jmartsch** [fixate/generator-fixate-pw#28]
Hi Larry,

my paths and filenames are different than yours. So it would be great if any directories or filenames are not in the gulpfile, but instead in the gulpconfig.json. So we are really flexible for every project. The concat task could look like this

```
gulp.task "concat", ["coffee"], () ->
  gulp.src [
    "#{conf.path.dev.coffee.concatArray}"
  ]
    .pipe concat( "#{conf.path.dev.js.concatDestFilename}")
    .pipe gulp.dest(conf.path.dev.js)
    .pipe bs.reload({stream: true})
```

Same thing for the minify:css or minify:js tasks. Or for the vendors file list.

What you think about this?

**Comment by larrybotha** [comment]
sounds like a good plan.

I really need to get around to converting that file to yml - the json file is getting clunky. It may even be a good idea to split this stuff out into multiple yml files in a `data/` folder.

Anyways, this seems like a nice OS agnostic way to solve your problem. Can you make a PR?
