### ISSUE TITLE
Inconsistent Histories

### ISSUE THREAD

**Issue by dewald-laubscher** [fixate/generator-fixate-pw#3]
Came across inconsistent history.

Inconsistent Branch History :
- https://github.com/fixate/generator-fixate-pw/blob/master/app/generator.coffee#L106-L121
- https://github.com/fixate/generator-fixate-pw/blob/develop/app/generator.coffee#L107-L125 

Possible solution:
- Create a release in git flow
- Should merge history in develop to master

**Comment by larrybotha** [comment]
fixed: https://github.com/fixate/generator-fixate-pw/issues/2#issuecomment-72442732
