### ISSUE TITLE
Site-profile removed on master branch 

### ISSUE THREAD

**Issue by bitlinguist** [fixate/generator-fixate-pw#31]
@larrybotha I saw a commit referencing the removal of site profile with an enquiry as to what that is. When processwire is downloaded there are a few site profiles downloaded along with it. These are the initial profiles for processwire. They determine what is initially installed. The site profile also contains initialized database install if I am not mistaken. 

"A site profile represents a full ProcessWire site ready to be installed." ~ http://modules.processwire.com/categories/site-profile/. 

I remember implementing this a while ago. The reason for this was that the modules are installed initially. Here the fixate site profile is installed:
https://github.com/fixate/generator-fixate-pw/blob/develop/app/generator.coffee#L116-L123

the site profile can be found here:
https://github.com/fixate/pw-mvc-boilerplate-site-profile

This breaks the initial install of processwire due to the following lines of code:
https://github.com/fixate/generator-fixate-pw/blob/develop/app/generator.coffee#L111
https://github.com/fixate/generator-fixate-pw/blob/develop/app/generator.coffee#L142-L147

Let me know if I can assist in clarifying this further.

**Comment by larrybotha** [comment]
there was something in the generator that was throwing an error around the point where the profile gets downloaded.

re-added it, and everything seems to be fine.

https://github.com/fixate/generator-fixate-pw/commit/08ce6f1d7924def4c61376ac36f0e297cc50135c
