### ISSUE TITLE
Improve sass error handling

### ISSUE THREAD

**Issue by bitlinguist** [fixate/generator-fixate-pw#33]
gulp-sass task exits when throwing an error. I have written a piece of code to fix that. Would you like me to make a pull request?

.pipe sass().on 'error', (err) ->
      new gutil.PluginError('CSS', err, {showStack: true})
      gutil.log err
      @emit('end')

**Comment by larrybotha** [comment]
https://github.com/fixate/generator-fixate-pw/commit/3d5bf20e6c60244ee639cf4f27d35885e76980ef should fix it - let me know if it's still exiting

**Comment by bitlinguist** [comment]
Thats perfect, Thanks! 

I made a pr, but it is inconsistent with the new release and you already did the fix. I can't seem to close it myself.
