### ISSUE TITLE
Maybe we can add gulp ftp 

### ISSUE THREAD

**Issue by bitlinguist** [fixate/generator-fixate-pw#35]
Add FTP
Here is a gist that I made:

It basically checks for files to change, add them to a file and then uploads each file in the said file.

I can implement this In a week or two from now:
https://gist.github.com/bitlinguist/38a94428ab5851b81537

**Comment by larrybotha** [comment]
not too keen on ftp bloat in the gulpfile, but it may turn out useful at some point. Looking forward to the progress on this.

**Comment by bitlinguist** [comment]
Cool :), I found it useful when the client has no ssh. This usually comes in to play with big companies that have their own server set up. 

Might also speed up deployment as ftp is faster based on some test I saw that benchmarked the speed. However I am aware that this might have been a selling point for ssh on your side, therefore this might be misinformation.

Keen on hearing your insights on this.

**Comment by larrybotha** [comment]
FTP is faster, but security may be a concern, as transfers are not encrypted: http://serverfault.com/a/158797
https://delightlylinux.wordpress.com/2013/06/26/which-is-faster-ssh-or-ftp/

Despite being slower for transfer, SSH is the preferred standard. DigitalOcean, Amazon, Linode etc. enforce all access via SSH for their services.

Can you do dry runs with FTP?

**Comment by bitlinguist** [comment]
Cool to learn about the industry standards.

Unfortunately I don't think it is possible. As I keep a list of changed files locally and only ftp them up. I am unaware of a way to check if the file has changed and then only push changed files. Deeper research might be needed on that question.
