### ISSUE TITLE
package.json syntax error

### ISSUE THREAD

**Issue by bjoernsteinborn** [fixate/generator-fixate-pw#40]
There is a comma missing after the gulp-if package in the app/templates/package.json

```
"gulp-if": "^2.0.1"
"webpack": "^1.13.1"
```
https://github.com/fixate/generator-fixate-pw/blob/master/app/templates/package.json#L54-L55

**Comment by larrybotha** [comment]
thanks @bjoernsteinborn - lazy copy pasting of modules into the generator while I'm working on projects
