### ISSUE TITLE
gulp-imagemin configuration outdated

### ISSUE THREAD

**Issue by bjoernsteinborn** [fixate/generator-fixate-pw#41]
The gulp-imagemin plugin configuration has changed with v3.
```
    .pipe(imagemin({
      optimizationLevel: 3,
      progressive: true,
      interlaced: true,
      svgoPlugins: [
        { removeViewBox: false },
        { cleanupIDs: false },
      ],
      ...
    }))
```
has to be 
```
    .pipe(imagemin([
      imagemin.gifsicle({ interlaced: true }),
      imagemin.jpegtran({ progressive: true }),
      imagemin.optipng({ optimizationLevel: 3 }),
      imagemin.svgo({ plugins: [
        { removeViewBox: false },
        { cleanupIDs: false },
      ] }),
```
now. (There are two more configuration block in the file.)

https://github.com/fixate/generator-fixate-pw/blob/master/app/templates/gulp/tasks/images.js#L40-L49

https://github.com/sindresorhus/gulp-imagemin#custom-plugin-options

**Comment by larrybotha** [comment]
thanks @bjoernsteinborn - tasks were still running on my side with the old configuration, but all it updated now

**Comment by bjoernsteinborn** [comment]
Yes, was also running for me but the config options at least for svgo were not reflected with the old setup. Thanks!

**Comment by larrybotha** [comment]
ok great - nice catch! I didn't notice any SVG problems, but I'm sure it woulda taken ages to figure out once I did.
