### ISSUE TITLE
allow ssh port to be configured via gulpconfig.json

### ISSUE THREAD

**Issue by larrybotha** [fixate/generator-fixate-pw#6]
some servers don't utilise the default port 21 for SSH.

gulp task should take a port in case the port needs to be changed.

default port in config should be 21.

gulp task should be on the lines of:

```coffee
ssh -p #{config.ssh.port} username@domain.com
```

**Comment by dewald-laubscher** [comment]
@larrybotha this is done

**Comment by larrybotha** [comment]
@dewald-laubscher line number?

**Comment by dewald-laubscher** [comment]
https://github.com/fixate/generator-fixate-pw/blob/master/app/templates/_gulpfile.coffee#L228
&&
https://github.com/fixate/generator-fixate-pw/blob/master/app/templates/_gulpconfig.json#L25

**Comment by larrybotha** [comment]
cool thanks
